exports.dirViews        = '/srv/Views/';
exports.dirCore         = '/srv/Core/';
exports.dirModels       = '/srv/Models/';
exports.dirControllers  = '/srv/Controllers/';
exports.dirPublic       = '/srv/Public/';
exports.dirBase         = '/srv/';
exports.dirNodeModules  = '/opt/node/lib/node_modules/';
exports.server          = require('http').createServer();
exports.io              = require(this.dirNodeModules+'socket.io').listen(this.server);
exports.fs              = require('fs');
exports.util            = require('util');
var JUST                = require(this.dirNodeModules+'just');
exports.View            = new JUST({ root : this.dirViews , useCache : true, ext : '.html' });
exports.formidable      = require(this.dirNodeModules+'formidable');        // работа с файлами
exports.logFile         = this.dirBase+'log.txt';
var app                 = require(this.dirCore+'App');
exports.App             = new app();
exports.eventReturnDataOfCallMethod = true; // при рассылке события отдавать получившиеся данные?